version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_store
      MYSQL_USER: nestjs_mysql
      MYSQL_PASSWORD: thaiquangqt2003
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 3
      start_period: 30s

  nestjs_app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: ['yarn', 'start:prod']

volumes:
  mysql_data:
